# Generated by Django 4.0.6 on 2022-07-25 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Birthdate', models.DateField(default=datetime.datetime(2022, 7, 25, 10, 12, 42, 208242))),
            ],
        ),
    ]
