# Generated by Django 4.0.6 on 2022-07-25 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_contact_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Birthdate',
            field=models.DateField(default=datetime.datetime(2022, 7, 25, 10, 29, 49, 794407)),
        ),
    ]
