# Generated by Django 4.0.6 on 2022-07-26 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_city_alter_contact_birthdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AlterField(
            model_name='contact',
            name='Birthdate',
            field=models.DateField(default=datetime.datetime(2022, 7, 26, 9, 36, 13, 66986)),
        ),
    ]
