# Generated by Django 4.0.6 on 2022-07-26 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_delete_city_alter_contact_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Birthdate',
            field=models.DateField(default=datetime.datetime(2022, 7, 26, 9, 59, 32, 186987)),
        ),
    ]
