# Generated by Django 4.0.6 on 2022-07-26 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_contact_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Birthdate',
            field=models.DateField(default=datetime.datetime(2022, 7, 26, 11, 9, 16, 468378)),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
