# Generated by Django 4.0.6 on 2022-08-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_rename_birthdate_contact_birth_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Birth_year',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Name',
        ),
        migrations.AddField(
            model_name='contact',
            name='X_axis',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='Y_axis',
            field=models.IntegerField(default=100),
        ),
    ]
