# Generated by Django 4.0.6 on 2022-08-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_remove_contact_birth_year_remove_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Description',
            field=models.CharField(default='Null', max_length=200),
            preserve_default=False,
        ),
    ]
