# Generated by Django 4.0.6 on 2022-08-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_contact_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='X_axis',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Y_axis',
        ),
    ]
