# Generated by Django 4.0.6 on 2022-08-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_remove_contact_x_axis_remove_contact_y_axis'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Image',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
