# Generated by Django 4.0.6 on 2022-08-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_contact_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Output',
            field=models.ImageField(blank=True, upload_to='new/'),
        ),
    ]
