# Generated by Django 4.0.6 on 2022-08-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_contact_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Output',
        ),
    ]
