# Generated by Django 4.0.6 on 2022-08-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_remove_contact_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Output',
            field=models.ImageField(blank=True, upload_to='new/'),
        ),
    ]
