# Generated by Django 4.0.6 on 2022-08-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_contact_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Image',
            new_name='Picture',
        ),
    ]
