# Generated by Django 4.0.6 on 2022-08-04 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_rename_image_contact_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Output',
        ),
    ]
