# Generated by Django 4.0.6 on 2022-08-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_remove_contact_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Picture',
            field=models.ImageField(upload_to='covers/'),
        ),
    ]
